version: "2"
services:
  app:
    environment:
      - MONGODB_URI=mongodb://mongo/app
    container_name: vmlist
    restart: always
    build: .
    ports:
      - "35000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db